name: Generate CVs

on:
  push:
    branches: [ main ]
    paths:
      - "andrei_cv_package/**/*.md"
      - ".github/workflows/generate-cv.yml"

permissions:
  contents: write

jobs:
  build-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-xetex tree

      - name: Generate PDFs
        run: |
          mkdir -p pdfs
          pandoc andrei_cv_package/CV_Andrei_Rusnac_ATS.md -o pdfs/CV_Andrei_Rusnac_ATS.pdf --pdf-engine=xelatex
          pandoc andrei_cv_package/CV_Andrei_Rusnac_Visual.md -o pdfs/CV_Andrei_Rusnac_Visual.pdf --pdf-engine=xelatex

      - name: List generated PDFs
        run: ls -l pdfs

      - name: Publish PDFs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: pdfs
          keep_files: true